title: Mya Tinsay
description: Testing my portolio?
theme: just-the-docs

url: https://Mya-Tinsay.github.io/Mya-Tinsay.github.io

aux_links:
  Template Repository: https://github.com/Mya-Tinsay/Mya-Tinsay.github.io
